---
all:
  hosts:
    armitage:
      ansible_host: 'armitage.pers'
      hostname: 'armitage'
      domainname: 'pers'
      ssh_port: '22'
      _ansible_user: 'ansibleuser'  # "ansible_user" is a builtin, we should probably use something better than just "_ansible_user" for our variable but w/e
      _ansible_ssh_key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDf6D7wvhtJtK9cJ3ruMBaiKsrjtziFzMtGV5QE2+FMz1ySkWsAG04Uu2ynDIOlcUT/+PhYMf4FNhmgTM0hLnpUG6Cz0gZ11bEsUTO4nJjk5mhTD6lrPJgYT6022hhnGh6rg/RNTwBrNxvN9qvs/ARX20fnZhZvU2im3A0/0nLf01BctqU/R8X2m+caZ7k1K+NqXOvofVRBBZEYWdE2scuQWOW1JAhG+GO3JUAlfPhAdT69qa6B4LFAu62FnWyssZMYIP3oSz2G+T5qjZDmFpb9Tgj/JkCaRaU8jtuxZjdEwi3HW1+bfvveoLmMNL7uk1pkOJ6iXAjlXZYHgXOHZcM5 epers@ansible-control'
      root_ssh_key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGqae2YFD5vxTb4w5sg44FyCJWjFazs8vPDXmXeUOrl2A2NhFt9A4oDNjFucOVDFEdIztXI9wpPwNb9NgmYNI+yCcbw9hKz5sOFQSk95+Ia3A0WOGRl6WEaQ/vTeU7bBdzADfqC/jxvUTh781KUTSoWa/S3KoiO/PRdzlcMxp0tRLOTBgucKMituvdB2Lpp08y825hrAwQOnHZcEoTjbyhHeZbAbB/G584rJtDkHFhi8PbrF2d+0wO/70STjwpIqlxhey75SrCSDiR1EUfTowKD2J3q1spZGAyCI0Csy2Q53b5I6k3TDA2O/UuAVmsbytFjdgA/EadCNuJV/2Km143 epers@neuromancer'
      root_password: '$6$5Sd0RWZsnD$UJchUZEEwX070YDAgJlfnwhq8cKdbVIn.XQxsaNia5PFFlMG5O556GiWPCKKoMqZzHZJSWUw3V2wrhROdL0ie0'
      disks: 
        - '/dev/disk/by-id/ata-SanDisk_SD6SF1M064G1022I_141837400760'
        - '/dev/disk/by-id/ata-SanDisk_SD6SF1M064G1022I_141837400397'
      network_interface:
        name: 'ens18'
        address_type: 'static'
        address: '192.168.155.30'
        prefix_length: '24'
