---
all:
  hosts:
    armitage:
      ansible_host: '192.168.161.57'
      hostname: 'armitage'
      domainname: 'pers'
      ssh_port: '2222'
      _ansible_user: 'ansibleuser'  # "ansible_user" is a builtin, we should probably use something better than just "_ansible_user" for our variable but w/e
      _ansible_ssh_key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGqae2YFD5vxTb4w5sg44FyCJWjFazs8vPDXmXeUOrl2A2NhFt9A4oDNjFucOVDFEdIztXI9wpPwNb9NgmYNI+yCcbw9hKz5sOFQSk95+Ia3A0WOGRl6WEaQ/vTeU7bBdzADfqC/jxvUTh781KUTSoWa/S3KoiO/PRdzlcMxp0tRLOTBgucKMituvdB2Lpp08y825hrAwQOnHZcEoTjbyhHeZbAbB/G584rJtDkHFhi8PbrF2d+0wO/70STjwpIqlxhey75SrCSDiR1EUfTowKD2J3q1spZGAyCI0Csy2Q53b5I6k3TDA2O/UuAVmsbytFjdgA/EadCNuJV/2Km143 epers@neuromancer'
      root_ssh_key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGqae2YFD5vxTb4w5sg44FyCJWjFazs8vPDXmXeUOrl2A2NhFt9A4oDNjFucOVDFEdIztXI9wpPwNb9NgmYNI+yCcbw9hKz5sOFQSk95+Ia3A0WOGRl6WEaQ/vTeU7bBdzADfqC/jxvUTh781KUTSoWa/S3KoiO/PRdzlcMxp0tRLOTBgucKMituvdB2Lpp08y825hrAwQOnHZcEoTjbyhHeZbAbB/G584rJtDkHFhi8PbrF2d+0wO/70STjwpIqlxhey75SrCSDiR1EUfTowKD2J3q1spZGAyCI0Csy2Q53b5I6k3TDA2O/UuAVmsbytFjdgA/EadCNuJV/2Km143 epers@neuromancer'
      root_password: '$6$5Sd0RWZsnD$UJchUZEEwX070YDAgJlfnwhq8cKdbVIn.XQxsaNia5PFFlMG5O556GiWPCKKoMqZzHZJSWUw3V2wrhROdL0ie0'
      disks: 
        - '/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi0'
        - '/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1'
      network_interface:
        name: 'ens18'
        address_type: 'static'
        address: '192.168.161.57'
        prefix_length: '22'
