---
all:
  hosts:
    armitage:
      ansible_host: '192.168.155.188'
      hostname: 'armitage'
      domainname: 'pers'
      ansible_user: 'ansible'
      ansible_ssh_key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDf6D7wvhtJtK9cJ3ruMBaiKsrjtziFzMtGV5QE2+FMz1ySkWsAG04Uu2ynDIOlcUT/+PhYMf4FNhmgTM0hLnpUG6Cz0gZ11bEsUTO4nJjk5mhTD6lrPJgYT6022hhnGh6rg/RNTwBrNxvN9qvs/ARX20fnZhZvU2im3A0/0nLf01BctqU/R8X2m+caZ7k1K+NqXOvofVRBBZEYWdE2scuQWOW1JAhG+GO3JUAlfPhAdT69qa6B4LFAu62FnWyssZMYIP3oSz2G+T5qjZDmFpb9Tgj/JkCaRaU8jtuxZjdEwi3HW1+bfvveoLmMNL7uk1pkOJ6iXAjlXZYHgXOHZcM5 epers@ansible-control'
      root_ssh_key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDf6D7wvhtJtK9cJ3ruMBaiKsrjtziFzMtGV5QE2+FMz1ySkWsAG04Uu2ynDIOlcUT/+PhYMf4FNhmgTM0hLnpUG6Cz0gZ11bEsUTO4nJjk5mhTD6lrPJgYT6022hhnGh6rg/RNTwBrNxvN9qvs/ARX20fnZhZvU2im3A0/0nLf01BctqU/R8X2m+caZ7k1K+NqXOvofVRBBZEYWdE2scuQWOW1JAhG+GO3JUAlfPhAdT69qa6B4LFAu62FnWyssZMYIP3oSz2G+T5qjZDmFpb9Tgj/JkCaRaU8jtuxZjdEwi3HW1+bfvveoLmMNL7uk1pkOJ6iXAjlXZYHgXOHZcM5 epers@ansible-control'
      root_password: '$6$5Sd0RWZsnD$UJchUZEEwX070YDAgJlfnwhq8cKdbVIn.XQxsaNia5PFFlMG5O556GiWPCKKoMqZzHZJSWUw3V2wrhROdL0ie0'
      disks: 
        - '/dev/disk/by-id/scsi-3600224807f62846c7ee89ecc063be1ba'
      