---

- name: install podman
  hosts: all
  become: yes
  gather_facts: false

  tasks:
    - name: 'Make sure we are using the {{ _ansible_user }} account'
      ansible.builtin.set_fact:
        ansible_ssh_user: '{{ _ansible_user }}'
        ansible_ssh_pass: ''
        ansible_sudo_pass: ''
        ansible_user: '{{ _ansible_user }}'

    - name: 'Gather facts'
      ansible.builtin.gather_facts:

    - name: update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: install packages
      ansible.builtin.apt:
        name: 
          - dirmngr
          - curl
          - python3
          - python3-pip
          - python3-setuptools
          - python-setuptools
        state: present
        install_recommends: true

    - name: add buster-backports repo
      ansible.builtin.apt_repository:
        repo: 'deb http://deb.debian.org/debian/ buster-backports main contrib non-free'
        state: present
    
    - name: add podman repo key
      ansible.builtin.apt_key:
        url: 'https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_10/Release.key'
        state: present
    
    - name: add podman repo
      ansible.builtin.apt_repository:
        repo: 'deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_10/ /'
        state: present

    - name: install libseccomp2 from backports
      ansible.builtin.apt:
        name: 
          - libseccomp2
        state: latest
        default_release: buster-backports
    
    - name: install packages
      ansible.builtin.apt:
        name: 
          - podman
        state: present
        install_recommends: true

    - name: install podman-compose
      ansible.builtin.pip:
        name: 
          - podman-compose
        executable: pip3

    - name: enable user namespaces
      ansible.posix.sysctl:
        name: 'kernel.unprivileged_userns_clone'
        value: 1
        state: present
        reload: true
