---
# this tasklist unmounts filesystems and reboots the system

- name: 'Switch back to livecd system'
  ansible.builtin.set_fact:
    ansible_ssh_user: '{{ _ansible_user }}'
    ansible_ssh_pass: ''
    ansible_sudo_pass: ''
    ansible_user: '{{ _ansible_user }}'
    ansible_ssh_port: '22'

- name: 'Kill all processes running under /mnt (with lsof)'
  ansible.builtin.shell:
    cmd: 'kill -9 $(lsof -t +D /mnt)'
    
- name: 'Copy /etc/hostid into chroot'
  ansible.builtin.shell:
    cmd: 'cp /etc/hostid /mnt/etc/hostid'

- name: 'Unmount all filesystems under /mnt'
  ansible.builtin.shell:
    cmd: 'umount -Rf /mnt'
  ignore_errors: yes

- name: 'Unmount all zfs filesystems'
  ansible.builtin.shell:
    cmd: 'zfs unmount -a'
  ignore_errors: yes

- name: 'Unmount filesystems'
  ansible.builtin.shell:
    cmd: "mount | grep -v zfs | tac | awk '/\/mnt/ {print $3}' | xargs -i{} umount -lf {}"
  ignore_errors: yes

- name: 'Export zpools'
  ansible.builtin.shell:
    cmd: 'zpool export -a -f'
  ignore_errors: yes

- name: 'Blind reboot system and exit playbook'
  ansible.builtin.shell:
    cmd: 'systemctl reboot'
  ignore_errors: yes
