---
# this tasklist is intended to be run against a debian livecd enviroment
# requires manual preparation - run "apt update && apt install -y openssh-server && systemctl start ssh
# TODO: roll my own livecd with ssh and ansible user already setup

- name: 'Make sure we're using the default "user" account provided by the livecd'
  ansible.builtin.set_fact:
    ansible_ssh_user: 'user'
    ansible_ssh_pass: 'live'
    ansible_sudo_pass: 'live'
    ansible_user: 'user'

- name: 'Gather facts'
  ansible.builtin.gather_facts:

- name: 'Create {{ ansible_user }} group'
  ansible.builtin.group:
    name: {{ ansible_user }}

- name: 'Create {{ ansible_user }} user'
  ansible.builtin.user:
    name: {{ ansible_user }}
    group: {{ ansible_user }}

- name: 'Set authorized key for {{ ansible_user }} from host variable'
  ansible.posix.authorized_key:
    user: ansible
    state: present
    key: {{ ansible_ssh_key }}

- name: 'Set passwordless sudo for {{ ansible_user }} user [/etc/sudoers.d/{{ ansible_user }}]'
  ansible.builtin.lineinfile:
    path: '/etc/sudoers.d/{{ ansible_user }}'
    line: '{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL'
    create: true

- name: 'Switch to our new {{ ansible_user }} user'
  ansible.builtin.set_fact:
    ansible_ssh_user: '{{ ansible_user }}'
    ansible_ssh_pass: ''
    ansible_sudo_pass: ''
    ansible_user: '{{ ansible_user }}'

- name: 'Remove default sources.list file'
  ansible.builtin.file:
    path: '/etc/apt/sources.list'
    state: absent

- name: 'Install live enviroment base dependencies'
  ansible.builtin.apt:
