---
# this tasklist is intended to be run against a debian livecd enviroment
# requires manual preparation - run "apt update && apt install -y openssh-server && systemctl start ssh
# TODO: roll my own livecd with ssh and ansible user already setup

- name: 'Make sure we are using the default "user" account provided by the livecd'
  ansible.builtin.set_fact:
    ansible_ssh_user: 'user'
    ansible_ssh_pass: 'live'
    ansible_sudo_pass: 'live'
    ansible_user: 'user'

- name: 'Gather facts'
  ansible.builtin.gather_facts:

- name: 'Create {{ _ansible_user }} group'
  ansible.builtin.group:
    name: '{{ _ansible_user }}'

- name: 'Create {{ _ansible_user }} user'
  ansible.builtin.user:
    name: '{{ _ansible_user }}'
    group: '{{ _ansible_user }}'

- name: 'Set authorized key for {{ _ansible_user }} from host variable'
  ansible.posix.authorized_key:
    user: '{{ _ansible_user }}'
    state: present
    key: '{{ _ansible_ssh_key }}'

- name: 'Set passwordless sudo for {{ _ansible_user }} user [/etc/sudoers.d/{{ _ansible_user }}]'
  ansible.builtin.lineinfile:
    path: '/etc/sudoers.d/{{ _ansible_user }}'
    line: '{{ _ansible_user }} ALL=(ALL) NOPASSWD: ALL'
    create: true

- name: 'Make sure we are using {{ _ansible_user }} user'
  ansible.builtin.set_fact:
    ansible_ssh_user: '{{ _ansible_user }}'
    ansible_ssh_pass: ''
    ansible_sudo_pass: ''
    ansible_user: '{{ _ansible_user }}'

- name: 'Install ansible prerequesites'
  ansible.builtin.apt:
    name:
      - 'python-apt'
    state: present
    update_cache: yes

- name: 'Remove default sources.list file'
  ansible.builtin.file:
    path: '/etc/apt/sources.list'
    state: absent

- name: 'Add main debian repo'
  ansible.builtin.apt_repository:
    repo: 'deb http://deb.debian.org/debian/ buster main non-free contrib'
    state: present

- name: 'Add buster-backports debian repo'
  ansible.builtin.apt_repository:
    repo: 'deb http://deb.debian.org/debian/ buster-backports main non-free contrib'
    state: present

- name: 'Update apt cache'
  ansible.builtin.apt:
    update_cache: yes

- name: 'Install live enviroment base dependencies'
  ansible.builtin.apt:
    name:
      - 'gdisk'
      - 'debootstrap'
      - 'dkms'
      - 'linux-headers-{{ ansible_kernel }}'

- name: 'Install zfs in the livecd'
  ansible.builtin.apt:
    default_release: buster-backports
    name:
      - zfs-dkms

- name: 'modprobe zfs'
  community.general.modprobe:
    name: 'zfs'
    state: present

- name: 'Install zfs in the livecd'
  ansible.builtin.apt:
    default_release: buster-backports
    name:
      - zfsutils-linux
