---
# CAUTION: this file will eat your disks for breakfast

# Make sure we're using the proper user - shouldn't need to do this but it's nice to be explicit
- name: 'Switch to our new {{ ansible_user }} user'
  ansible.builtin.set_fact:
    ansible_ssh_user: '{{ ansible_user }}'
    ansible_ssh_pass: ''
    ansible_sudo_pass: ''
    ansible_user: '{{ ansible_user }}'

- name: 'Gather facts'
  ansible.builtin.gather_facts:

- name: 'Read device information'
  community.general.parted: device={{ item }} unit=MiB
  register: 'disk_info'
  loop: '{{ disks }}'

- name: Remove all partitions from disk
  community.general.parted:
    device: '{{ item.0.item }}'
    number: '{{ item.1.num }}'
    state: absent
  loop: "{{ disk_info.results|subelements('partitions')}}"
