---
# this tasklist installs zfs packages and creates the zpool/zfs layout we need

- name: 'Make sure we are using {{ ansible_user }} user'
  ansible.builtin.set_fact:
    ansible_ssh_user: '{{ ansible_user }}'
    ansible_ssh_pass: ''
    ansible_sudo_pass: ''
    ansible_user: '{{ ansible_user }}'

- name: 'Gather facts'
  ansible.builtin.gather_facts:

